estimation implementation for both non gasless and gasless flow
aarc-xyz/aarc-sdk pull request #25
Opened 2023-11-21 03:43 UTC by talhamalik883

2023-11-22 07:26 UTC, anshulforyou requested changes
Please make sure that in gasless the ERC20Permit transaction is happening first with the  new flow as well.

2023-11-22 07:26 UTC, anshulforyou commented on src/AarcSDK.ts
> +      if (tokenAddresses && tokenAddresses.length > 0) {
What's the purpose of this code block?

2023-11-22 07:26 UTC, anshulforyou commented on src/helpers/PermitHelper.ts
> +      const nonce = await this.getPermit2Nonce(eoaAddress);
Here permit2 nonce will give wrong nonce. This function is signing msg for ERC20Permit contract. Here the nonce is calculated through the nonces function only. The previous code was right.

2023-11-22 12:12 UTC, anshulforyou requested changes

2023-11-22 12:12 UTC, anshulforyou commented on tests/AarcSDK.test.ts
> +  it('should handle a successful migration for native token only', async () => {
Please create a different test suite file for native tokens

2023-11-22 18:26 UTC, talhamalik883 commented on src/helpers/PermitHelper.ts
> +      const nonce = await this.getPermit2Nonce(eoaAddress);
done

2023-11-22 18:26 UTC, talhamalik883 commented on tests/AarcSDK.test.ts
> +  it('should handle a successful migration for native token only', async () => {
done

2023-11-22 18:26 UTC, talhamalik883 commented on src/AarcSDK.ts
> +  ETHEREUM_ADDRESS,
done

2023-11-22 18:28 UTC, talhamalik883 commented on src/AarcSDK.ts
> +      if (tokenAddresses && tokenAddresses.length > 0) {
If the user is going to supply token addresses, we will include native tokens to retrieve their balances as well. This way, we can verify if the native token holds enough value to facilitate the transfer of tokens.

2023-11-23 08:14 UTC, anshulforyou requested changes
We should add case in tests when the required gas is not there. What would be the response in that case?

2023-11-23 19:27 UTC, anshulforyou approved these changes

2023-11-23 19:28 UTC, merged